### ISSUE TITLE
To much padding to the right of the site logo

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.canonical.com#10]
There is currently: 

``` css
header.banner .nav-primary.nav-right .logo-ubuntu {
    min-width: 156px;
}
```

should be:

``` css
header.banner .nav-primary.nav-right .logo-ubuntu {
    min-width: 127px;
}
```
