### ISSUE TITLE
Footer links are missing styling

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.canonical.com#15]
On live there is the following styling which is missing from the demo:

``` css
footer.global p, 
footer.global ul.inline li a {  
  color: #333;
  font-size: 12px;
  margin-bottom: 0;
}
```
