### ISSUE TITLE
Contextual footer 

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.canonical.com#18]
Can you update the contextual footer feature padding to compensate for the different vertical divider component.

``` css
.row-contextual-footer .featured p {
    padding-right: 140px; /* was 150px */
}
```
