### ISSUE TITLE
Footer > find out more is missing its :before

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.canonical.com#19]
In the footer the h2 "Find out more" is missing its external icon which is added with a before.

``` css
.yes-js #additional-info h2:before {
  -moz-background-size: 14px 14px;
  -webkit-background-size: 14px 14px;
  -o-background-size: 14px 14px;
  background-size: 14px 14px;
  background-image: url('/static/img/external-link-grey.png');
  background-image: url('/static/img/external-link-9fa097.svg'), none;
  background-repeat: no-repeat;
  content: "";
  display: inline-block;
  height: 15px;
  width: 15px;
  margin-right: 3px;
  top: 3px;
  position: relative;
}
```

_Just remove the js check_
