### ISSUE TITLE
[partners] Missing white box around partners

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.canonical.com#23]
Missing box-white styling for the partners list:

``` css
.box-white {
  background: #fff;
  -moz-border-radius: 4px;
  -webkit-border-radius: 4px;
  border-radius: 4px;
  color: #333;
  padding: 1.333em 20px;
}
```
