### ISSUE TITLE
Missing last-item and last-of-type on li's

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.canonical.com#26]
Know this is probably a Vanilla issue but missing:

``` css
li:last-of-type {
  margin-bottom: 0;
}
```
